name: Main Pipeline

on:
    - push
    - pull_request

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            DENO_DIR: cache_deps
        steps:
            - name: Checkout do código
              uses: actions/checkout@v4

            - name: Configurar Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Adicionando dependencia manual
              run: deno install --allow-scripts=npm:protobufjs@7.4.0

            - name: Verificando formatação do código
              run: deno task fmt

            - name: Verificando linter
              run: deno task lint

            - name: Executar testes
              run: deno task test
